add_subdirectory(actionids)
add_subdirectory(cpudetect)
add_subdirectory(gamedirs)
add_subdirectory(ini)
add_subdirectory(logstress)
add_subdirectory(netpacket)
add_subdirectory(sosparity)
add_subdirectory(spawner)
add_subdirectory(spawnhouse)
add_subdirectory(syncrec)
add_subdirectory(colorops)
add_subdirectory(voxeldraw)
add_subdirectory(unvqdec)
add_subdirectory(lcwcomp)
add_subdirectory(lcwblock)
add_subdirectory(autosave)
add_subdirectory(desync)
